# Generated by Django 5.1.1 on 2024-09-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Rut')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=30, verbose_name='Apellido')),
                ('dob', models.DateField(verbose_name='Fecha Nacimiento')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleado',
                'ordering': ['lastname', 'name', 'rut'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['name'], 'verbose_name': 'artículo', 'verbose_name_plural': 'artículos'},
        ),
    ]
